src/de/thb/jee/ledger/ui/EntryController.java
package de.thb.jee.ledger.ui;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.format.TextStyle;
import java.util.Map;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import de.thb.jee.ledger.logic.LedgerService;
import de.thb.jee.ledger.models.Entry;

@Named
@RequestScoped
public class EntryController implements Serializable {

  private static final long serialVersionUID = 623556647812397099L;
  private Entry entry;
  //propertyActionListener gets called after all setters so we need a copy of the oldEntry
  private Entry oldEntry;
  private Double saldo;

  @Inject
  private LedgerService ledgerService;
  @Inject
  private PageState pageState;

  public EntryController() {
    this.reset();
  }

  public void reset() {
    this.entry = new Entry();
    this.oldEntry = new Entry();
    this.saldo = null;
  }

  public Entry getEntry() {
    return this.entry;
  }

  public void setEntry(Entry entry) {
    this.entry = entry;
  }

  public void setOldEntry(Entry entry) {
    this.oldEntry = entry;
  }

  public String getTitle() {
    return this.entry.getTitle();
  }

  public void setTitle(String title) {
    this.entry.setTitle(title);
  }

  public double getValue() {
    return this.entry.getValue();
  }

  public void setValue(double value) {
    this.entry.setValue(value);
  }

  public LocalDateTime getDate() {
    return this.entry.getDate();
  }

  public void setDate(LocalDateTime date) {
    this.entry.setDate(date);
  }

  public String getPayer() {
    return this.entry.getPayer();
  }

  public void setPayer(String payer) {
    this.entry.setPayer(payer);
  }

  public char getType() {
    if (this.entry.getValue() <= 0) {
      return '-';
    } else {
      return '+';
    }
  }

  public void setType(String type) {
    double oldValue = this.entry.getValue();
    double value = oldValue;
    switch(type) {
      case "-": value = (oldValue < 0) ? oldValue : -oldValue; break;
      case "+": value = (oldValue < 0) ? -oldValue : oldValue; break;
    }

    this.entry.setValue(value);
  }

  public String delete() {
    ledgerService.deleteEntry(oldEntry);
    this.pageState.setEntries(null);
    return null;
  }

  public String save() {
    Map<String, String> requestParams = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
    this.setType(requestParams.get("type"));
    this.setFormattedDate(requestParams.get("date"));
    if(this.oldEntry != null) {
      this.entry.setId(this.oldEntry.getId());
    }
    if(this.entry.getPage() == null) {
      this.entry.setPage(this.pageState.getPage());
    }
    this.ledgerService.createEntry(this.entry);
    this.pageState.setEntries(null);
    this.reset();
    return null;
  }

  public int getDay() {
    return this.entry.getDate().getDayOfMonth();
  }

  public int getMonth() {
    return this.entry.getDate().getMonth().getValue();
  }

  public String getMonthTwoDigits() {
    return String.format("%02d", this.getMonth());
  }

  public String getMonthShort() {
    return this.entry.getDate().getMonth().getDisplayName(TextStyle.SHORT, FacesContext.getCurrentInstance().getViewRoot().getLocale());
  }

  public int getYear() {
    return this.entry.getDate().getYear();
  }

  public String getFormattedDate() {
    return this.ledgerService.getFormattedDateString(this.entry.getDate());
  }

  public void setFormattedDate(String formattedDate) {
    this.entry.setDate(this.ledgerService.getDateFromFormattedString(formattedDate));
  }

  public Double getSaldo() {
    if(this.saldo == null) {
      this.saldo=ledgerService.getSaldo(this.entry.getPage().getId(), this.entry.getDate(), this.entry.getId());
    }
    return this.saldo;
  }
}

src/de/thb/jee/ledger/ui/PageController.java
package de.thb.jee.ledger.ui;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.temporal.TemporalAdjusters;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import de.thb.jee.ledger.logic.LedgerService;
import de.thb.jee.ledger.models.Entry;
import de.thb.jee.ledger.models.Page;

@Named
@RequestScoped
public class PageController {

  @Inject
  private LedgerService ledgerService;
  @Inject
  private PageState pageState;
  @Inject
  private FilterController filterController;
  private int show;
  private static final int DEFAULT_STEP = 10;

  public PageController() {
    this.show = 10;
  }

  public String showMore (int oldShow) {
    this.show = oldShow + DEFAULT_STEP;
    return null;
  }

  public List<Entry> getEntriesReverse() {
    return this.ledgerService.getEntriesReverseDate(this.getPage().getId());
  }

  public Page getPage() {
    return this.pageState.getPage();
  }

  @PostConstruct
  public void setPage() {
    if (this.pageState.getPage() == null) {
      this.pageState.setPage(this.ledgerService.getAllPages().get(0));
    }
  }

  public List<Entry> getEntries() {
    if (this.pageState.getEntries() == null) {
      this.pageState.setEntries(this.getEntriesReverse());
    }
    return this.pageState.getEntries();
  }

  public Entry getPreviousEntry(int index) {
    Entry result = null;
    if(index > 0) {
    result = this.getEntries().get(index - 1);
      return result;
    }
    if(result == null) {
      result = this.getEntries().get(index);
    }
    return result;
  }

  public int getShow() {
    return show;
  }

  public void setShow(int show) {
    this.show = show;
  }

  public String summary() {
    return this.summary(null);
  }

  public String summary(LocalDateTime date) {
    if (date != null) {
      LocalDateTime start = date.with(TemporalAdjusters.firstDayOfMonth());
      start = start.with(LocalTime.MIN);
      LocalDateTime end = date.with(TemporalAdjusters.lastDayOfMonth());
      end = end.with(LocalTime.MAX);
      this.filterController.setBeginDate(start);
      this.filterController.setEndDate(end);
      this.filterController.filterEntries();
    }
    return "summary";
  }
}

WebContent/components/advanced_filters.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:l="http://jee.thb.de/ledger">
  <h:panelGroup layout="block" class="filter-container" id="filter-container">
    <div class="item">
      <label>Payer</label>
      <h:inputText class="form-control" a:placeholder="Enter the payer" value="#{filterController.payer}" autocomplete="off"/>
    </div>
    <div class="item">
      <label>Value</label>
      <div class="input-group">
        <div class="input-group-prepend btn-group btn-group-toggle type" data-toggle="buttons">
          <label class="btn btn-outline-dark #{filterController.comparator eq '&lt;=' ? 'active' : null}">
            <input type="radio" name="comparator" autocomplete="off" value="&lt;=" checked="#{filterController.comparator eq '&lt;=' ? 'checked' : null}"/> &lt;=
          </label>
          <label class="btn btn-outline-dark #{filterController.comparator eq '=' ? 'active' : null}">
            <input type="radio" name="comparator" autocomplete="off" value="=" checked="#{filterController.comparator eq '=' ? 'checked' : null}"/> =
          </label>
          <label class="btn btn-outline-dark #{filterController.comparator eq '&gt;=' ? 'active' : null}">
            <input type="radio" name="comparator" autocomplete="off" value="&gt;=" checked="#{filterController.comparator eq '&gt;=' ? 'checked' : null}"/> &gt;=
          </label>
        </div>
        <h:inputText class="form-control" a:placeholder="0.00" value="#{filterController.threshold}" autocomplete="off">
          <l:positiveCurrencyConverter />
        </h:inputText>
      </div>
    </div>

    <div class="item">
      <label>Start Date</label>
      <div class="datepicker-container" data-date="#{filterController.beginDate}">
            <input type="hidden" class="form-control" name="beginDate" value="#{filterController.beginDate}"/>
      </div>
    </div>
    <div class="item">
      <label>End Date</label>
      <div class="datepicker-container" data-date="#{filterController.endDate}">
            <input type="hidden" class="form-control" name="endDate" value="#{filterController.endDate}"/>
      </div>
    </div>

    <div class="item workflow-buttons">
      <h:commandButton class="btn btn-outline-success filter-trigger" value="Filter" action="#{filterController.filter}">
        <f:ajax render="transaction-list summary-dirty" execute="@form" />
      </h:commandButton>
      <h:commandButton class="btn btn-outline-danger filter-trigger" value="Clear" action="#{filterController.clear}">
        <f:ajax render="transaction-list summary-dirty filter-form" execute="@form" />
      </h:commandButton>
    </div>
  </h:panelGroup>
</ui:composition>

WebContent/components/entry_overlay.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:jsf="http://xmlns.jcp.org/jsf"
    xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:l="http://jee.thb.de/ledger">
  <h:form>
    <div class="overlay #{overlayType}-overlay">
      <div class="overlay-background #{overlayType}-overlay-background"></div>
        <div class="overlay-container overlay-container-left">
          <header>
            #{headerText}
            <div class="right">
              <span class="fa fa-times fa-lg header-button #{overlayType}-overlay-close"></span>
            </div>
          </header>
          <div class="spacer"></div>
          <div class="create-form overlay-content">
            <div class="title-date-container item">
            <div class="title-container">
            <label for="titel">Titel</label>
              <h:inputText class="text-input" a:placeholder="Enter a title" value="#{entryController.title}" autocomplete="off"/>
              </div>
              <div class="date-container">
                <div class="btn-group-vertical" data-toggle="buttons">
                  <button class="btn btn-outline-dark date-button month">
                    #{entryController.monthShort}
                  </button>
                  <button class="btn btn-outline-dark date-button day">
                    #{entryController.day}
                  </button>
                </div>
              </div>
            </div>
            <div class="payer-container">
            <label for="payer">Payer</label>
            <h:inputText class="item text-input" a:placeholder="Enter the payer" value="#{entryController.payer}" autocomplete="off"/>
            </div>
            <div class="cost-container item">
              <div class="btn-group-vertical btn-group-toggle type" data-toggle="buttons">
                <label class="btn btn-outline-dark #{entryController.type eq '-' ? 'active' : null}">
                  <input type="radio" name="type" autocomplete="off" value="-" checked="#{entryController.type eq '-' ? 'checked' : null}"/> Expense
                </label>
                <label class="btn btn-outline-dark #{entryController.type eq '+' ? 'active' : null}">
                  <input type="radio" name="type" autocomplete="off" value="+" checked="#{entryController.type eq '+' ? 'checked' : null}"/> Income
                </label>
              </div>
              <div class="input-group">
                <h:panelGroup rendered="false" class="input-group-prepend currency-dropdown">
                  <button class="btn btn-dark dropdown-toggle" type="button" data-toggle="dropdown">€</button>
                  <div class="dropdown dropdown-menu">
                    <a class="dropdown-item" href="#">€</a>
                    <a class="dropdown-item" href="#">$</a>
                  </div>
                </h:panelGroup>
                <h:inputText a:placeholder="0.00" value="#{entryController.value}" class="form-control">
                 <l:positiveCurrencyConverter />
                </h:inputText>
              </div>
            </div>
            <div class="save-delete-buttons">
              <h:commandButton rendered="#{overlayType eq 'item'}" class="btn btn-outline-danger #{overlayType}-overlay-close" value="Delete" action="#{entryController.delete}">
                <f:setPropertyActionListener target="#{entryController.oldEntry}" value="#{entry}" />
                <f:ajax render="content create" execute="@form" />
              </h:commandButton>
              <h:commandButton class="btn btn-outline-success #{overlayType}-overlay-close" value="Save" action="#{entryController.save}">
                <f:setPropertyActionListener target="#{entryController.oldEntry}" value="#{entry}" />
                <f:ajax render="content create" execute="@form" />
              </h:commandButton>
            </div>
          </div>
        </div>
        <div class="overlay-container overlay-container-right">
          <div class="datepicker-container" data-date="#{entryController.formattedDate}">
            <input type="hidden" class="form-control" name="date" value="#{entryController.formattedDate}"/>
          </div>
        </div>
    </div>
  </h:form>
</ui:composition>

WebContent/components/settings-overlay.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:a="http://xmlns.jcp.org/jsf/passthrough">
  <div class="overlay" id="settings-overlay">
    <div class="overlay-background" id="settings-overlay-background"></div>
    <div class="overlay-container">
      <header>
        Settings
        <span class="fa fa-times fa-lg header-button settings-overlay-close"></span>
      </header>
      <div class="spacer"></div>
      <div class="overlay-content">
        <h:form>
          <div class="item">
            <label class="slider-btn" for="light-switch">
              <h:selectBooleanCheckbox a:id="light-switch" value="#{settingsController.darkmode}"/>
              <div class="slider round"></div>
            </label>
            <div class="label">Dark mode</div>
          </div>
          <h:commandButton class="btn btn-outline-success settings-overlay-close" value="Save" action="#{settingsController.save}">
            <f:ajax execute="@form" />
          </h:commandButton>
        </h:form>
      </div>
    </div>
  </div>
</ui:composition>

WebContent/components/template.xhtml
<!DOCTYPE html>
<html xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
  <h:head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://momentjs.com/downloads/moment.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>

    <!-- only needed in summary page but h:outputStylesheet does not support external links, so it's needed here -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chartist/0.11.0/chartist.min.css" />
    <link rel="stylesheet" href="https://cdn.rawgit.com/tmmdata/chartist-plugin-tooltip/130146dd/dist/chartist-plugin-tooltip.css" />

    <link rel="stylesheet" type="text/css" href="css/styles.css" />
    <link rel="stylesheet" type="text/css" href="css/scrollbar.css" />

  </h:head>
  <h:body class="#{settingsController.darkmode ? 't-dark': ''}">

    <div class="main">
      <ui:insert name="header">
        <h:form id="filter-form">
          <div class="header">
            <span class="listname">#{pageController.page.title}</span>
            <ui:insert name="inner-header">
              <div class="searchbox input-group">
                <h:inputText class="form-control button-outline-dark" id="filter-title"
                  placeholder="Search for..."
                  value="#{filterController.title}" />
                <div class="input-group-append">
                  <button class="btn btn-outline-dark filter-trigger" type="button"></button>
                  <button type="button" class="btn btn-outline-success create-item-trigger">Add Bill</button>
                </div>
              </div>
            </ui:insert>
            <span class="fa fa-cog fa-lg settings" id="settings-trigger"></span>
          </div>
          <ui:insert name="filter">
            <ui:include src="advanced_filters.xhtml"></ui:include>
          </ui:insert>
        </h:form>
        <div class="spacer"></div>
      </ui:insert>
      <h:panelGroup layout="block" class="content" id="content">
        <ui:insert name="content"></ui:insert>
      </h:panelGroup>
    </div>

    <ui:insert name="additional" id="additional">
      <h:panelGroup id="create">
        #{entryController.reset()}
        <ui:include src="entry_overlay.xhtml">
          <ui:param name="headerText" value="Add a bill" />
          <ui:param name="overlayType" value="create" />
        </ui:include>
      </h:panelGroup>

      <ui:include src="settings-overlay.xhtml"></ui:include>

      <ui:insert name="inner-additional"></ui:insert>
    </ui:insert>

    <script src="js/utilities/cssClass.js"></script>
    <script src="js/overlay.js"></script>
    <h:panelGroup rendered="false">
      <script src="js/dropdown.js"></script> <!-- needed for currency-dropdown, which is not implemented yet-->
    </h:panelGroup>
    <script src="js/datepicker.js"></script>
    <script src="js/jsf-ajax-fix.js"></script>
  </h:body>
</html>

WebContent/components/transaction-list.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:l="http://jee.thb.de/ledger">
  <h:panelGroup class="transaction-list" id="transaction-list">
    <div class="list-spacer">
      <h:form>
        <h:commandButton class="btn btn-link" value="Complete Summary" action="#{pageController.summary()}" />
      </h:form>
    </div>
    <c:forEach items="#{pageController.entries}" var="entry" varStatus="metadata" end="#{pageController.show - 1}">
      #{entryController.setEntry(entry)}
      <h:panelGroup rendered="#{metadata.index == 0 or entry.date.month.value lt pageController.getPreviousEntry(metadata.index).date.month.value}">
        <div class="list-spacer month-spacer">
          <span>#{entryController.monthShort} #{entryController.year}</span>
          <h:form>
            <h:commandButton class="btn btn-link" value="Summary" action="#{pageController.summary(entry.date)}" />
          </h:form>
        </div>
      </h:panelGroup>
      <div class="transaction-container">
        <div class="transaction item-trigger">
          <div class="left">
            <div class="day">
              #{entryController.monthShort}<div class="number">#{entryController.day}</div>
            </div>
            <span class="title">#{entryController.title}</span>
          </div>
          <div class="right">
            <span class="value #{entry.value le 0 ? 'negative' : 'positive' }">
              <h:outputText value="#{entry.value}">
                <l:positiveCurrencyConverter symbol="€"/>
              </h:outputText>
            </span>
            <span class="value #{entryController.saldo le 0 ? 'negative' : 'positive' }">
              <h:outputText value="#{entryController.saldo}">
                <l:positiveCurrencyConverter symbol="€"/>
              </h:outputText>
            </span>
          </div>
        </div>
        <ui:include src="entry_overlay.xhtml">
          <ui:param name="entry" value="#{entry}" />
          <ui:param name="headerText" value="Bill" />
          <ui:param name="overlayType" value="item" />
        </ui:include>
      </div>
      #{entryController.reset()}
    </c:forEach>
    <h:form class="more" rendered="#{pageController.show lt pageController.entries.size()}">
      <h:commandButton class="btn btn-outline-dark" value="Show more" action="#{pageController.showMore(pageController.show)}">
        <f:ajax render="transaction-list" execute="@form"/>
      </h:commandButton>
      <h:inputHidden value="#{pageController.show}"/>
    </h:form>
  </h:panelGroup>
</ui:composition>